name: chat-components-pr

on:
  pull_request:
    branches:
      - '**'
    types: [created, edited, assigned, opened, synchronize, reopened]
    paths:
      - 'chat-components/**'
      
jobs: 
  build:
    runs-on: windows-2019
    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.X
      - name: Install packages
        working-directory: chat-components
        run: yarn install
      - name: Unit Tests
        working-directory: chat-components
        run: yarn test:unit
      - name: Build Storybook
        working-directory: chat-components
        run: yarn build-storybook
      - name: VRT Tests
        working-directory: chat-components
        run: yarn test:visual
      - name: Upload VRT Tests failures screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: VRT Failure Screenshots
          path: 'chat-components/**/__diff_output__/*.png'
      - name: Build package
        working-directory: chat-components
        run: yarn build
